name: Create Release with Changelog
on:
  push:
    branches:
      - main
jobs:
  create_release:
    name: Create Release with Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Generate Changelog
        id: changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.nextChangelog }}
          draft: false
          prerelease: false
